// Generated by purs bundle 0.13.8
var PS = {};
(function(exports) {
  "use strict";

  exports.showNumberImpl = function (n) {
    var str = n.toString();
    return isNaN(str + ".0") ? str : str + ".0";
  };
})(PS["Data.Show"] = PS["Data.Show"] || {});
(function($PS) {
  // Generated by purs version 0.13.8
  "use strict";
  $PS["Data.Show"] = $PS["Data.Show"] || {};
  var exports = $PS["Data.Show"];
  var $foreign = $PS["Data.Show"];
  var Show = function (show) {
      this.show = show;
  };
  var showNumber = new Show($foreign.showNumberImpl);
  var show = function (dict) {
      return dict.show;
  };
  exports["show"] = show;
  exports["showNumber"] = showNumber;
})(PS);
(function(exports) {
  "use strict";

  exports.log = function (s) {
    return function () {
      console.log(s);
      return {};
    };
  };
})(PS["Effect.Console"] = PS["Effect.Console"] || {});
(function($PS) {
  // Generated by purs version 0.13.8
  "use strict";
  $PS["Effect.Console"] = $PS["Effect.Console"] || {};
  var exports = $PS["Effect.Console"];
  var $foreign = $PS["Effect.Console"];
  exports["log"] = $foreign.log;
})(PS);
(function(exports) {
  "use strict";

  exports.getGameGlobal = function(){ return Game; }
})(PS["Screeps.Game"] = PS["Screeps.Game"] || {});
(function(exports) {
  "use strict";

  // module Screeps.FFI

  exports.unsafeField = function(key){
      return function(obj){
          return obj[key];
      }
  }
  exports.runThisEffFn0 = function(key){
      return function(self){
          return function(){
              return self[key]();
          }
      }
  }
})(PS["Screeps.FFI"] = PS["Screeps.FFI"] || {});
(function($PS) {
  // Generated by purs version 0.13.8
  "use strict";
  $PS["Screeps.FFI"] = $PS["Screeps.FFI"] || {};
  var exports = $PS["Screeps.FFI"];
  var $foreign = $PS["Screeps.FFI"];
  exports["unsafeField"] = $foreign.unsafeField;
  exports["runThisEffFn0"] = $foreign.runThisEffFn0;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.8
  "use strict";
  $PS["Screeps.Game"] = $PS["Screeps.Game"] || {};
  var exports = $PS["Screeps.Game"];
  var $foreign = $PS["Screeps.Game"];
  var Screeps_FFI = $PS["Screeps.FFI"];                
  var cpu = Screeps_FFI.unsafeField("cpu");
  var getUsed = function (game) {
      return Screeps_FFI.runThisEffFn0("getUsed")(cpu(game));
  };
  exports["getUsed"] = getUsed;
  exports["getGameGlobal"] = $foreign.getGameGlobal;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.8
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var Data_Show = $PS["Data.Show"];
  var Effect_Console = $PS["Effect.Console"];
  var Screeps_Game = $PS["Screeps.Game"];                
  var main = function __do() {
      var game = Screeps_Game.getGameGlobal();
      var startUsed = Screeps_Game.getUsed(game)();
      Effect_Console.log("start: " + Data_Show.show(Data_Show.showNumber)(startUsed))();
      return Effect_Console.log("blop")();
  };
  exports["main"] = main;
})(PS);
PS["Main"].main();