// Generated by purs bundle 0.14.5
var PS = {};
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Control.Apply"] = $PS["Control.Apply"] || {};
  var exports = $PS["Control.Apply"];
  var apply = function (dict) {
      return dict.apply;
  };
  exports["apply"] = apply;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Control.Applicative"] = $PS["Control.Applicative"] || {};
  var exports = $PS["Control.Applicative"];
  var Control_Apply = $PS["Control.Apply"];          
  var pure = function (dict) {
      return dict.pure;
  };
  var liftA1 = function (dictApplicative) {
      return function (f) {
          return function (a) {
              return Control_Apply.apply(dictApplicative.Apply0())(pure(dictApplicative)(f))(a);
          };
      };
  };
  exports["pure"] = pure;
  exports["liftA1"] = liftA1;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Function"] = $PS["Data.Function"] || {};
  var exports = $PS["Data.Function"];
  var flip = function (f) {
      return function (b) {
          return function (a) {
              return f(a)(b);
          };
      };
  };
  var $$const = function (a) {
      return function (v) {
          return a;
      };
  };
  var applyFlipped = function (x) {
      return function (f) {
          return f(x);
      };
  };
  exports["flip"] = flip;
  exports["const"] = $$const;
  exports["applyFlipped"] = applyFlipped;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Control.Bind"] = $PS["Control.Bind"] || {};
  var exports = $PS["Control.Bind"];
  var Data_Function = $PS["Data.Function"];
  var bind = function (dict) {
      return dict.bind;
  };
  var bindFlipped = function (dictBind) {
      return Data_Function.flip(bind(dictBind));
  };
  var composeKleisliFlipped = function (dictBind) {
      return function (f) {
          return function (g) {
              return function (a) {
                  return bindFlipped(dictBind)(f)(g(a));
              };
          };
      };
  };
  exports["bind"] = bind;
  exports["composeKleisliFlipped"] = composeKleisliFlipped;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Control.Semigroupoid"] = $PS["Control.Semigroupoid"] || {};
  var exports = $PS["Control.Semigroupoid"];
  var semigroupoidFn = {
      compose: function (f) {
          return function (g) {
              return function (x) {
                  return f(g(x));
              };
          };
      }
  };
  exports["semigroupoidFn"] = semigroupoidFn;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Control.Category"] = $PS["Control.Category"] || {};
  var exports = $PS["Control.Category"];
  var Control_Semigroupoid = $PS["Control.Semigroupoid"];                
  var identity = function (dict) {
      return dict.identity;
  };
  var categoryFn = {
      identity: function (x) {
          return x;
      },
      Semigroupoid0: function () {
          return Control_Semigroupoid.semigroupoidFn;
      }
  };
  exports["identity"] = identity;
  exports["categoryFn"] = categoryFn;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Control.Monad"] = $PS["Control.Monad"] || {};
  var exports = $PS["Control.Monad"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Bind = $PS["Control.Bind"];
  var ap = function (dictMonad) {
      return function (f) {
          return function (a) {
              return Control_Bind.bind(dictMonad.Bind1())(f)(function (f$prime) {
                  return Control_Bind.bind(dictMonad.Bind1())(a)(function (a$prime) {
                      return Control_Applicative.pure(dictMonad.Applicative0())(f$prime(a$prime));
                  });
              });
          };
      };
  };
  exports["ap"] = ap;
})(PS);
(function(exports) {
  "use strict";

  exports.map_ = function (f) {
    return function (a) {
      return function () {
        return f(a());
      };
    };
  };

  exports.pure_ = function (a) {
    return function () {
      return a;
    };
  };

  exports.bind_ = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };
})(PS["Control.Monad.ST.Internal"] = PS["Control.Monad.ST.Internal"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Control.Monad.ST.Internal"] = $PS["Control.Monad.ST.Internal"] || {};
  var exports = $PS["Control.Monad.ST.Internal"];
  var $foreign = $PS["Control.Monad.ST.Internal"];
  var Control_Monad = $PS["Control.Monad"];
  var functorST = {
      map: $foreign.map_
  };
  var monadST = {
      Applicative0: function () {
          return applicativeST;
      },
      Bind1: function () {
          return bindST;
      }
  };
  var bindST = {
      bind: $foreign.bind_,
      Apply0: function () {
          return applyST;
      }
  };
  var applyST = {
      apply: Control_Monad.ap(monadST),
      Functor0: function () {
          return functorST;
      }
  };
  var applicativeST = {
      pure: $foreign.pure_,
      Apply0: function () {
          return applyST;
      }
  };
  exports["applicativeST"] = applicativeST;
  exports["monadST"] = monadST;
})(PS);
(function(exports) {
  /* eslint-disable no-eq-null, eqeqeq */
  "use strict";

  function id(x) {
    return x;
  }                        
  exports.fromNumber = id;
  exports.fromString = id;
  exports.fromObject = id;

  exports.jsonNull = null;

  exports.stringify = function (j) {
    return JSON.stringify(j);
  };

  exports._caseJson = function (isNull, isBool, isNum, isStr, isArr, isObj, j) {
    if (j == null) return isNull();
    else if (typeof j === "boolean") return isBool(j);
    else if (typeof j === "number") return isNum(j);
    else if (typeof j === "string") return isStr(j);
    else if (Object.prototype.toString.call(j) === "[object Array]")
      return isArr(j);
    else return isObj(j);
  };
})(PS["Data.Argonaut.Core"] = PS["Data.Argonaut.Core"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Maybe"] = $PS["Data.Maybe"] || {};
  var exports = $PS["Data.Maybe"];                 
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  var maybe = function (v) {
      return function (v1) {
          return function (v2) {
              if (v2 instanceof Nothing) {
                  return v;
              };
              if (v2 instanceof Just) {
                  return v1(v2.value0);
              };
              throw new Error("Failed pattern match at Data.Maybe (line 230, column 1 - line 230, column 51): " + [ v.constructor.name, v1.constructor.name, v2.constructor.name ]);
          };
      };
  };
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;
  exports["maybe"] = maybe;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Argonaut.Core"] = $PS["Data.Argonaut.Core"] || {};
  var exports = $PS["Data.Argonaut.Core"];
  var $foreign = $PS["Data.Argonaut.Core"];
  var Data_Function = $PS["Data.Function"];
  var Data_Maybe = $PS["Data.Maybe"];                        
  var verbJsonType = function (def) {
      return function (f) {
          return function (g) {
              return g(def)(f);
          };
      };
  };
  var toJsonType = verbJsonType(Data_Maybe.Nothing.value)(Data_Maybe.Just.create);
  var isJsonType = verbJsonType(false)(Data_Function["const"](true));
  var caseJsonString = function (d) {
      return function (f) {
          return function (j) {
              return $foreign["_caseJson"](Data_Function["const"](d), Data_Function["const"](d), Data_Function["const"](d), f, Data_Function["const"](d), Data_Function["const"](d), j);
          };
      };
  };                                        
  var caseJsonObject = function (d) {
      return function (f) {
          return function (j) {
              return $foreign["_caseJson"](Data_Function["const"](d), Data_Function["const"](d), Data_Function["const"](d), Data_Function["const"](d), Data_Function["const"](d), f, j);
          };
      };
  };                                        
  var toObject = toJsonType(caseJsonObject);
  var caseJsonNumber = function (d) {
      return function (f) {
          return function (j) {
              return $foreign["_caseJson"](Data_Function["const"](d), Data_Function["const"](d), f, Data_Function["const"](d), Data_Function["const"](d), Data_Function["const"](d), j);
          };
      };
  };                                        
  var caseJsonNull = function (d) {
      return function (f) {
          return function (j) {
              return $foreign["_caseJson"](f, Data_Function["const"](d), Data_Function["const"](d), Data_Function["const"](d), Data_Function["const"](d), Data_Function["const"](d), j);
          };
      };
  };
  var isNull = isJsonType(caseJsonNull);
  exports["caseJsonNumber"] = caseJsonNumber;
  exports["caseJsonString"] = caseJsonString;
  exports["isNull"] = isNull;
  exports["toObject"] = toObject;
  exports["fromNumber"] = $foreign.fromNumber;
  exports["fromString"] = $foreign.fromString;
  exports["fromObject"] = $foreign.fromObject;
  exports["jsonNull"] = $foreign.jsonNull;
  exports["stringify"] = $foreign.stringify;
})(PS);
(function(exports) {
  "use strict";

  exports.showIntImpl = function (n) {
    return n.toString();
  };
})(PS["Data.Show"] = PS["Data.Show"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Show"] = $PS["Data.Show"] || {};
  var exports = $PS["Data.Show"];
  var $foreign = $PS["Data.Show"];
  var showInt = {
      show: $foreign.showIntImpl
  };
  var show = function (dict) {
      return dict.show;
  };
  exports["show"] = show;
  exports["showInt"] = showInt;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Argonaut.Decode.Error"] = $PS["Data.Argonaut.Decode.Error"] || {};
  var exports = $PS["Data.Argonaut.Decode.Error"];
  var Data_Argonaut_Core = $PS["Data.Argonaut.Core"];
  var Data_Show = $PS["Data.Show"];                
  var TypeMismatch = (function () {
      function TypeMismatch(value0) {
          this.value0 = value0;
      };
      TypeMismatch.create = function (value0) {
          return new TypeMismatch(value0);
      };
      return TypeMismatch;
  })();
  var UnexpectedValue = (function () {
      function UnexpectedValue(value0) {
          this.value0 = value0;
      };
      UnexpectedValue.create = function (value0) {
          return new UnexpectedValue(value0);
      };
      return UnexpectedValue;
  })();
  var AtIndex = (function () {
      function AtIndex(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      AtIndex.create = function (value0) {
          return function (value1) {
              return new AtIndex(value0, value1);
          };
      };
      return AtIndex;
  })();
  var AtKey = (function () {
      function AtKey(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      AtKey.create = function (value0) {
          return function (value1) {
              return new AtKey(value0, value1);
          };
      };
      return AtKey;
  })();
  var Named = (function () {
      function Named(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Named.create = function (value0) {
          return function (value1) {
              return new Named(value0, value1);
          };
      };
      return Named;
  })();
  var MissingValue = (function () {
      function MissingValue() {

      };
      MissingValue.value = new MissingValue();
      return MissingValue;
  })();
  var printJsonDecodeError = function (err) {
      var go = function (v) {
          if (v instanceof TypeMismatch) {
              return "  Expected value of type '" + (v.value0 + "'.");
          };
          if (v instanceof UnexpectedValue) {
              return "  Unexpected value " + (Data_Argonaut_Core.stringify(v.value0) + ".");
          };
          if (v instanceof AtIndex) {
              return "  At array index " + (Data_Show.show(Data_Show.showInt)(v.value0) + (":\x0a" + go(v.value1)));
          };
          if (v instanceof AtKey) {
              return "  At object key '" + (v.value0 + ("':\x0a" + go(v.value1)));
          };
          if (v instanceof Named) {
              return "  Under '" + (v.value0 + ("':\x0a" + go(v.value1)));
          };
          if (v instanceof MissingValue) {
              return "  No value was found.";
          };
          throw new Error("Failed pattern match at Data.Argonaut.Decode.Error (line 37, column 8 - line 43, column 44): " + [ v.constructor.name ]);
      };
      return "An error occurred while decoding a JSON value:\x0a" + go(err);
  };
  exports["TypeMismatch"] = TypeMismatch;
  exports["AtKey"] = AtKey;
  exports["Named"] = Named;
  exports["MissingValue"] = MissingValue;
  exports["printJsonDecodeError"] = printJsonDecodeError;
})(PS);
(function(exports) {
  "use strict";

  exports.arrayMap = function (f) {
    return function (arr) {
      var l = arr.length;
      var result = new Array(l);
      for (var i = 0; i < l; i++) {
        result[i] = f(arr[i]);
      }
      return result;
    };
  };
})(PS["Data.Functor"] = PS["Data.Functor"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Functor"] = $PS["Data.Functor"] || {};
  var exports = $PS["Data.Functor"];
  var $foreign = $PS["Data.Functor"];                
  var map = function (dict) {
      return dict.map;
  };
  var functorArray = {
      map: $foreign.arrayMap
  };
  exports["map"] = map;
  exports["functorArray"] = functorArray;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Either"] = $PS["Data.Either"] || {};
  var exports = $PS["Data.Either"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_Maybe = $PS["Data.Maybe"];              
  var Left = (function () {
      function Left(value0) {
          this.value0 = value0;
      };
      Left.create = function (value0) {
          return new Left(value0);
      };
      return Left;
  })();
  var Right = (function () {
      function Right(value0) {
          this.value0 = value0;
      };
      Right.create = function (value0) {
          return new Right(value0);
      };
      return Right;
  })();
  var note = function (a) {
      return Data_Maybe.maybe(new Left(a))(Right.create);
  };
  var functorEither = {
      map: function (f) {
          return function (m) {
              if (m instanceof Left) {
                  return new Left(m.value0);
              };
              if (m instanceof Right) {
                  return new Right(f(m.value0));
              };
              throw new Error("Failed pattern match at Data.Either (line 31, column 1 - line 31, column 52): " + [ m.constructor.name ]);
          };
      }
  };
  var either = function (v) {
      return function (v1) {
          return function (v2) {
              if (v2 instanceof Left) {
                  return v(v2.value0);
              };
              if (v2 instanceof Right) {
                  return v1(v2.value0);
              };
              throw new Error("Failed pattern match at Data.Either (line 208, column 1 - line 208, column 64): " + [ v.constructor.name, v1.constructor.name, v2.constructor.name ]);
          };
      };
  };
  var applyEither = {
      apply: function (v) {
          return function (v1) {
              if (v instanceof Left) {
                  return new Left(v.value0);
              };
              if (v instanceof Right) {
                  return Data_Functor.map(functorEither)(v.value0)(v1);
              };
              throw new Error("Failed pattern match at Data.Either (line 70, column 1 - line 72, column 30): " + [ v.constructor.name, v1.constructor.name ]);
          };
      },
      Functor0: function () {
          return functorEither;
      }
  };
  var bindEither = {
      bind: either(function (e) {
          return function (v) {
              return new Left(e);
          };
      })(function (a) {
          return function (f) {
              return f(a);
          };
      }),
      Apply0: function () {
          return applyEither;
      }
  };
  var applicativeEither = {
      pure: Right.create,
      Apply0: function () {
          return applyEither;
      }
  };
  exports["Left"] = Left;
  exports["Right"] = Right;
  exports["note"] = note;
  exports["functorEither"] = functorEither;
  exports["applicativeEither"] = applicativeEither;
  exports["bindEither"] = bindEither;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Bifunctor"] = $PS["Data.Bifunctor"] || {};
  var exports = $PS["Data.Bifunctor"];
  var Control_Category = $PS["Control.Category"];
  var Data_Either = $PS["Data.Either"];              
  var bimap = function (dict) {
      return dict.bimap;
  };
  var lmap = function (dictBifunctor) {
      return function (f) {
          return bimap(dictBifunctor)(f)(Control_Category.identity(Control_Category.categoryFn));
      };
  };
  var bifunctorEither = {
      bimap: function (v) {
          return function (v1) {
              return function (v2) {
                  if (v2 instanceof Data_Either.Left) {
                      return new Data_Either.Left(v(v2.value0));
                  };
                  if (v2 instanceof Data_Either.Right) {
                      return new Data_Either.Right(v1(v2.value0));
                  };
                  throw new Error("Failed pattern match at Data.Bifunctor (line 32, column 1 - line 34, column 36): " + [ v.constructor.name, v1.constructor.name, v2.constructor.name ]);
              };
          };
      }
  };
  exports["lmap"] = lmap;
  exports["bifunctorEither"] = bifunctorEither;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Boolean"] = $PS["Data.Boolean"] || {};
  var exports = $PS["Data.Boolean"];
  var otherwise = true;
  exports["otherwise"] = otherwise;
})(PS);
(function(exports) {
  "use strict";

  exports.fromNumberImpl = function (just) {
    return function (nothing) {
      return function (n) {
        /* jshint bitwise: false */
        return (n | 0) === n ? just(n) : nothing;
      };
    };
  };

  exports.toNumber = function (n) {
    return n;
  };


  exports.quot = function (x) {
    return function (y) {
      /* jshint bitwise: false */
      return x / y | 0;
    };
  };
})(PS["Data.Int"] = PS["Data.Int"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Int"] = $PS["Data.Int"] || {};
  var exports = $PS["Data.Int"];
  var $foreign = $PS["Data.Int"];
  var Data_Maybe = $PS["Data.Maybe"];
  var fromNumber = $foreign.fromNumberImpl(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  exports["fromNumber"] = fromNumber;
  exports["toNumber"] = $foreign.toNumber;
  exports["quot"] = $foreign.quot;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Traversable"] = $PS["Data.Traversable"] || {};
  var exports = $PS["Data.Traversable"];             
  var traverse = function (dict) {
      return dict.traverse;
  };
  exports["traverse"] = traverse;
})(PS);
(function(exports) {
  "use strict";

  exports._copyST = function (m) {
    return function () {
      var r = {};
      for (var k in m) {
        if (hasOwnProperty.call(m, k)) {
          r[k] = m[k];
        }
      }
      return r;
    };
  };

  exports.empty = {};

  exports.runST = function (f) {
    return f();
  };

  exports._fmapObject = function (m0, f) {
    var m = {};
    for (var k in m0) {
      if (hasOwnProperty.call(m0, k)) {
        m[k] = f(m0[k]);
      }
    }
    return m;
  };

  exports._mapWithKey = function (m0, f) {
    var m = {};
    for (var k in m0) {
      if (hasOwnProperty.call(m0, k)) {
        m[k] = f(k)(m0[k]);
      }
    }
    return m;
  };

  exports._foldM = function (bind) {
    return function (f) {
      return function (mz) {
        return function (m) {
          var acc = mz;
          function g(k) {
            return function (z) {
              return f(z)(k)(m[k]);
            };
          }
          for (var k in m) {
            if (hasOwnProperty.call(m, k)) {
              acc = bind(acc)(g(k));
            }
          }
          return acc;
        };
      };
    };
  };

  exports.all = function (f) {
    return function (m) {
      for (var k in m) {
        if (hasOwnProperty.call(m, k) && !f(k)(m[k])) return false;
      }
      return true;
    };
  };

  exports.size = function (m) {
    var s = 0;
    for (var k in m) {
      if (hasOwnProperty.call(m, k)) {
        ++s;
      }
    }
    return s;
  };

  exports._lookup = function (no, yes, k, m) {
    return k in m ? yes(m[k]) : no;
  };

  function toArrayWithKey(f) {
    return function (m) {
      var r = [];
      for (var k in m) {
        if (hasOwnProperty.call(m, k)) {
          r.push(f(k)(m[k]));
        }
      }
      return r;
    };
  }

  exports.toArrayWithKey = toArrayWithKey;
})(PS["Foreign.Object"] = PS["Foreign.Object"] || {});
(function(exports) {
  "use strict";

  exports.foldrArray = function (f) {
    return function (init) {
      return function (xs) {
        var acc = init;
        var len = xs.length;
        for (var i = len - 1; i >= 0; i--) {
          acc = f(xs[i])(acc);
        }
        return acc;
      };
    };
  };

  exports.foldlArray = function (f) {
    return function (init) {
      return function (xs) {
        var acc = init;
        var len = xs.length;
        for (var i = 0; i < len; i++) {
          acc = f(acc)(xs[i]);
        }
        return acc;
      };
    };
  };
})(PS["Data.Foldable"] = PS["Data.Foldable"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Monoid"] = $PS["Data.Monoid"] || {};
  var exports = $PS["Data.Monoid"];
  var mempty = function (dict) {
      return dict.mempty;
  };
  exports["mempty"] = mempty;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Semigroup"] = $PS["Data.Semigroup"] || {};
  var exports = $PS["Data.Semigroup"];
  var append = function (dict) {
      return dict.append;
  };
  exports["append"] = append;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Foldable"] = $PS["Data.Foldable"] || {};
  var exports = $PS["Data.Foldable"];
  var $foreign = $PS["Data.Foldable"];
  var Data_Monoid = $PS["Data.Monoid"];
  var Data_Semigroup = $PS["Data.Semigroup"];      
  var foldr = function (dict) {
      return dict.foldr;
  };
  var foldl = function (dict) {
      return dict.foldl;
  };
  var foldMapDefaultR = function (dictFoldable) {
      return function (dictMonoid) {
          return function (f) {
              return foldr(dictFoldable)(function (x) {
                  return function (acc) {
                      return Data_Semigroup.append(dictMonoid.Semigroup0())(f(x))(acc);
                  };
              })(Data_Monoid.mempty(dictMonoid));
          };
      };
  };
  var foldableArray = {
      foldr: $foreign.foldrArray,
      foldl: $foreign.foldlArray,
      foldMap: function (dictMonoid) {
          return foldMapDefaultR(foldableArray)(dictMonoid);
      }
  };
  exports["foldr"] = foldr;
  exports["foldl"] = foldl;
  exports["foldableArray"] = foldableArray;
})(PS);
(function(exports) {
  "use strict";

  exports.runFn4 = function (fn) {
    return function (a) {
      return function (b) {
        return function (c) {
          return function (d) {
            return fn(a, b, c, d);
          };
        };
      };
    };
  };
})(PS["Data.Function.Uncurried"] = PS["Data.Function.Uncurried"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Function.Uncurried"] = $PS["Data.Function.Uncurried"] || {};
  var exports = $PS["Data.Function.Uncurried"];
  var $foreign = $PS["Data.Function.Uncurried"];
  exports["runFn4"] = $foreign.runFn4;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.TraversableWithIndex"] = $PS["Data.TraversableWithIndex"] || {};
  var exports = $PS["Data.TraversableWithIndex"];
  var traverseWithIndex = function (dict) {
      return dict.traverseWithIndex;
  };
  exports["traverseWithIndex"] = traverseWithIndex;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Tuple"] = $PS["Data.Tuple"] || {};
  var exports = $PS["Data.Tuple"];                 
  var Tuple = (function () {
      function Tuple(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Tuple.create = function (value0) {
          return function (value1) {
              return new Tuple(value0, value1);
          };
      };
      return Tuple;
  })();
  var uncurry = function (f) {
      return function (v) {
          return f(v.value0)(v.value1);
      };
  };
  exports["Tuple"] = Tuple;
  exports["uncurry"] = uncurry;
})(PS);
(function(exports) {
  "use strict";

  exports["new"] = function () {
    return {};
  };

  exports.poke = function (k) {
    return function (v) {
      return function (m) {
        return function () {
          m[k] = v;
          return m;
        };
      };
    };
  };

  exports["delete"] = function (k) {
    return function (m) {
      return function () {
        delete m[k];
        return m;
      };
    };
  };
})(PS["Foreign.Object.ST"] = PS["Foreign.Object.ST"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Foreign.Object.ST"] = $PS["Foreign.Object.ST"] || {};
  var exports = $PS["Foreign.Object.ST"];
  var $foreign = $PS["Foreign.Object.ST"];
  exports["new"] = $foreign["new"];
  exports["poke"] = $foreign.poke;
  exports["delete"] = $foreign["delete"];
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Foreign.Object"] = $PS["Foreign.Object"] || {};
  var exports = $PS["Foreign.Object"];
  var $foreign = $PS["Foreign.Object"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Apply = $PS["Control.Apply"];
  var Control_Bind = $PS["Control.Bind"];
  var Control_Category = $PS["Control.Category"];
  var Control_Monad_ST_Internal = $PS["Control.Monad.ST.Internal"];
  var Data_Foldable = $PS["Data.Foldable"];
  var Data_Function = $PS["Data.Function"];
  var Data_Function_Uncurried = $PS["Data.Function.Uncurried"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Data_Monoid = $PS["Data.Monoid"];
  var Data_Semigroup = $PS["Data.Semigroup"];
  var Data_Traversable = $PS["Data.Traversable"];
  var Data_TraversableWithIndex = $PS["Data.TraversableWithIndex"];
  var Data_Tuple = $PS["Data.Tuple"];
  var Foreign_Object_ST = $PS["Foreign.Object.ST"];        
  var values = $foreign.toArrayWithKey(function (v) {
      return function (v1) {
          return v1;
      };
  });                                                            
  var thawST = $foreign["_copyST"];
  var mutate = function (f) {
      return function (m) {
          return $foreign.runST(function __do() {
              var s = thawST(m)();
              f(s)();
              return s;
          });
      };
  };                                                                                                    
  var mapWithKey = function (f) {
      return function (m) {
          return $foreign["_mapWithKey"](m, f);
      };
  };
  var lookup = Data_Function_Uncurried.runFn4($foreign["_lookup"])(Data_Maybe.Nothing.value)(Data_Maybe.Just.create);
  var isEmpty = $foreign.all(function (v) {
      return function (v1) {
          return false;
      };
  });
  var insert = function (k) {
      return function (v) {
          return mutate(Foreign_Object_ST.poke(k)(v));
      };
  };
  var functorObject = {
      map: function (f) {
          return function (m) {
              return $foreign["_fmapObject"](m, f);
          };
      }
  };
  var functorWithIndexObject = {
      mapWithIndex: mapWithKey,
      Functor0: function () {
          return functorObject;
      }
  };
  var foldM = function (dictMonad) {
      return function (f) {
          return function (z) {
              return $foreign["_foldM"](Control_Bind.bind(dictMonad.Bind1()))(f)(Control_Applicative.pure(dictMonad.Applicative0())(z));
          };
      };
  };
  var fold = $foreign["_foldM"](Data_Function.applyFlipped);
  var foldMap = function (dictMonoid) {
      return function (f) {
          return fold(function (acc) {
              return function (k) {
                  return function (v) {
                      return Data_Semigroup.append(dictMonoid.Semigroup0())(acc)(f(k)(v));
                  };
              };
          })(Data_Monoid.mempty(dictMonoid));
      };
  };
  var foldableObject = {
      foldl: function (f) {
          return fold(function (z) {
              return function (v) {
                  return f(z);
              };
          });
      },
      foldr: function (f) {
          return function (z) {
              return function (m) {
                  return Data_Foldable.foldr(Data_Foldable.foldableArray)(f)(z)(values(m));
              };
          };
      },
      foldMap: function (dictMonoid) {
          return function (f) {
              return foldMap(dictMonoid)(Data_Function["const"](f));
          };
      }
  };
  var foldableWithIndexObject = {
      foldlWithIndex: function (f) {
          return fold(Data_Function.flip(f));
      },
      foldrWithIndex: function (f) {
          return function (z) {
              return function (m) {
                  return Data_Foldable.foldr(Data_Foldable.foldableArray)(Data_Tuple.uncurry(f))(z)($foreign.toArrayWithKey(Data_Tuple.Tuple.create)(m));
              };
          };
      },
      foldMapWithIndex: function (dictMonoid) {
          return foldMap(dictMonoid);
      },
      Foldable0: function () {
          return foldableObject;
      }
  };
  var traversableWithIndexObject = {
      traverseWithIndex: function (dictApplicative) {
          return function (f) {
              return function (ms) {
                  return fold(function (acc) {
                      return function (k) {
                          return function (v) {
                              return Control_Apply.apply(dictApplicative.Apply0())(Data_Functor.map((dictApplicative.Apply0()).Functor0())(Data_Function.flip(insert(k)))(acc))(f(k)(v));
                          };
                      };
                  })(Control_Applicative.pure(dictApplicative)($foreign.empty))(ms);
              };
          };
      },
      FunctorWithIndex0: function () {
          return functorWithIndexObject;
      },
      FoldableWithIndex1: function () {
          return foldableWithIndexObject;
      },
      Traversable2: function () {
          return traversableObject;
      }
  };
  var traversableObject = {
      traverse: function (dictApplicative) {
          var $43 = Data_TraversableWithIndex.traverseWithIndex(traversableWithIndexObject)(dictApplicative);
          return function ($44) {
              return $43(Data_Function["const"]($44));
          };
      },
      sequence: function (dictApplicative) {
          return Data_Traversable.traverse(traversableObject)(dictApplicative)(Control_Category.identity(Control_Category.categoryFn));
      },
      Functor0: function () {
          return functorObject;
      },
      Foldable1: function () {
          return foldableObject;
      }
  };
  var filterWithKey = function (predicate) {
      return function (m) {
          var go = (function () {
              var step = function (acc) {
                  return function (k) {
                      return function (v) {
                          var $33 = predicate(k)(v);
                          if ($33) {
                              return Foreign_Object_ST.poke(k)(v)(acc);
                          };
                          return Control_Applicative.pure(Control_Monad_ST_Internal.applicativeST)(acc);
                      };
                  };
              };
              return function __do() {
                  var m$prime = Foreign_Object_ST["new"]();
                  return foldM(Control_Monad_ST_Internal.monadST)(step)(m$prime)(m)();
              };
          })();
          return $foreign.runST(go);
      };
  };
  var filter = function (predicate) {
      return filterWithKey(Data_Function["const"](predicate));
  };
  var $$delete = function (k) {
      return mutate(Foreign_Object_ST["delete"](k));
  };
  var alter = function (f) {
      return function (k) {
          return function (m) {
              var v = f(lookup(k)(m));
              if (v instanceof Data_Maybe.Nothing) {
                  return $$delete(k)(m);
              };
              if (v instanceof Data_Maybe.Just) {
                  return insert(k)(v.value0)(m);
              };
              throw new Error("Failed pattern match at Foreign.Object (line 209, column 15 - line 211, column 25): " + [ v.constructor.name ]);
          };
      };
  };
  var update = function (f) {
      return function (k) {
          return function (m) {
              return alter(Data_Maybe.maybe(Data_Maybe.Nothing.value)(f))(k)(m);
          };
      };
  };
  exports["isEmpty"] = isEmpty;
  exports["lookup"] = lookup;
  exports["update"] = update;
  exports["mapWithKey"] = mapWithKey;
  exports["filter"] = filter;
  exports["functorObject"] = functorObject;
  exports["traversableObject"] = traversableObject;
  exports["empty"] = $foreign.empty;
  exports["size"] = $foreign.size;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Argonaut.Decode.Decoders"] = $PS["Data.Argonaut.Decode.Decoders"] || {};
  var exports = $PS["Data.Argonaut.Decode.Decoders"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Bind = $PS["Control.Bind"];
  var Data_Argonaut_Core = $PS["Data.Argonaut.Core"];
  var Data_Argonaut_Decode_Error = $PS["Data.Argonaut.Decode.Error"];
  var Data_Bifunctor = $PS["Data.Bifunctor"];
  var Data_Boolean = $PS["Data.Boolean"];
  var Data_Either = $PS["Data.Either"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_Int = $PS["Data.Int"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Data_Traversable = $PS["Data.Traversable"];
  var Foreign_Object = $PS["Foreign.Object"];
  var getField = function (decoder) {
      return function (obj) {
          return function (str) {
              return Data_Maybe.maybe(Data_Either.Left.create(new Data_Argonaut_Decode_Error.AtKey(str, Data_Argonaut_Decode_Error.MissingValue.value)))((function () {
                  var $18 = Data_Bifunctor.lmap(Data_Bifunctor.bifunctorEither)(Data_Argonaut_Decode_Error.AtKey.create(str));
                  return function ($19) {
                      return $18(decoder($19));
                  };
              })())(Foreign_Object.lookup(str)(obj));
          };
      };
  };
  var decodeString = Data_Argonaut_Core.caseJsonString(Data_Either.Left.create(new Data_Argonaut_Decode_Error.TypeMismatch("String")))(Data_Either.Right.create);
  var decodeNumber = Data_Argonaut_Core.caseJsonNumber(Data_Either.Left.create(new Data_Argonaut_Decode_Error.TypeMismatch("Number")))(Data_Either.Right.create);
  var decodeMaybe = function (decoder) {
      return function (json) {
          if (Data_Argonaut_Core.isNull(json)) {
              return Control_Applicative.pure(Data_Either.applicativeEither)(Data_Maybe.Nothing.value);
          };
          if (Data_Boolean.otherwise) {
              return Data_Functor.map(Data_Either.functorEither)(Data_Maybe.Just.create)(decoder(json));
          };
          throw new Error("Failed pattern match at Data.Argonaut.Decode.Decoders (line 37, column 1 - line 41, column 38): " + [ decoder.constructor.name, json.constructor.name ]);
      };
  };
  var decodeJObject = (function () {
      var $20 = Data_Either.note(new Data_Argonaut_Decode_Error.TypeMismatch("Object"));
      return function ($21) {
          return $20(Data_Argonaut_Core.toObject($21));
      };
  })();
  var decodeInt = Control_Bind.composeKleisliFlipped(Data_Either.bindEither)((function () {
      var $54 = Data_Either.note(new Data_Argonaut_Decode_Error.TypeMismatch("Integer"));
      return function ($55) {
          return $54(Data_Int.fromNumber($55));
      };
  })())(decodeNumber);
  var decodeForeignObject = function (decoder) {
      return Control_Bind.composeKleisliFlipped(Data_Either.bindEither)((function () {
          var $56 = Data_Bifunctor.lmap(Data_Bifunctor.bifunctorEither)(Data_Argonaut_Decode_Error.Named.create("ForeignObject"));
          var $57 = Data_Traversable.traverse(Foreign_Object.traversableObject)(Data_Either.applicativeEither)(decoder);
          return function ($58) {
              return $56($57($58));
          };
      })())(decodeJObject);
  };
  exports["decodeMaybe"] = decodeMaybe;
  exports["decodeInt"] = decodeInt;
  exports["decodeString"] = decodeString;
  exports["decodeForeignObject"] = decodeForeignObject;
  exports["getField"] = getField;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Argonaut.Decode.Class"] = $PS["Data.Argonaut.Decode.Class"] || {};
  var exports = $PS["Data.Argonaut.Decode.Class"];
  var Data_Argonaut_Decode_Decoders = $PS["Data.Argonaut.Decode.Decoders"];
  var Data_Either = $PS["Data.Either"];
  var decodeJsonString = {
      decodeJson: Data_Argonaut_Decode_Decoders.decodeString
  };
  var decodeJsonJson = {
      decodeJson: Data_Either.Right.create
  };
  var decodeJsonInt = {
      decodeJson: Data_Argonaut_Decode_Decoders.decodeInt
  };
  var decodeJson = function (dict) {
      return dict.decodeJson;
  };
  var decodeJsonMaybe = function (dictDecodeJson) {
      return {
          decodeJson: Data_Argonaut_Decode_Decoders.decodeMaybe(decodeJson(dictDecodeJson))
      };
  };
  var decodeForeignObject = function (dictDecodeJson) {
      return {
          decodeJson: Data_Argonaut_Decode_Decoders.decodeForeignObject(decodeJson(dictDecodeJson))
      };
  };
  exports["decodeJson"] = decodeJson;
  exports["decodeJsonMaybe"] = decodeJsonMaybe;
  exports["decodeJsonInt"] = decodeJsonInt;
  exports["decodeJsonString"] = decodeJsonString;
  exports["decodeJsonJson"] = decodeJsonJson;
  exports["decodeForeignObject"] = decodeForeignObject;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Argonaut.Decode.Combinators"] = $PS["Data.Argonaut.Decode.Combinators"] || {};
  var exports = $PS["Data.Argonaut.Decode.Combinators"];
  var Data_Argonaut_Decode_Class = $PS["Data.Argonaut.Decode.Class"];
  var Data_Argonaut_Decode_Decoders = $PS["Data.Argonaut.Decode.Decoders"];
  var getField = function (dictDecodeJson) {
      return Data_Argonaut_Decode_Decoders.getField(Data_Argonaut_Decode_Class.decodeJson(dictDecodeJson));
  };
  exports["getField"] = getField;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Argonaut.Encode.Encoders"] = $PS["Data.Argonaut.Encode.Encoders"] || {};
  var exports = $PS["Data.Argonaut.Encode.Encoders"];
  var Data_Argonaut_Core = $PS["Data.Argonaut.Core"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_Int = $PS["Data.Int"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Foreign_Object = $PS["Foreign.Object"];
  var encodeString = Data_Argonaut_Core.fromString;
  var encodeMaybe = function (encoder) {
      return function (v) {
          if (v instanceof Data_Maybe.Nothing) {
              return Data_Argonaut_Core.jsonNull;
          };
          if (v instanceof Data_Maybe.Just) {
              return encoder(v.value0);
          };
          throw new Error("Failed pattern match at Data.Argonaut.Encode.Encoders (line 31, column 23 - line 33, column 22): " + [ v.constructor.name ]);
      };
  };
  var encodeInt = function ($48) {
      return Data_Argonaut_Core.fromNumber(Data_Int.toNumber($48));
  };
  var encodeForeignObject = function (encoder) {
      var $49 = Data_Functor.map(Foreign_Object.functorObject)(encoder);
      return function ($50) {
          return Data_Argonaut_Core.fromObject($49($50));
      };
  };
  exports["encodeMaybe"] = encodeMaybe;
  exports["encodeInt"] = encodeInt;
  exports["encodeString"] = encodeString;
  exports["encodeForeignObject"] = encodeForeignObject;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Argonaut.Encode.Class"] = $PS["Data.Argonaut.Encode.Class"] || {};
  var exports = $PS["Data.Argonaut.Encode.Class"];
  var Control_Category = $PS["Control.Category"];
  var Data_Argonaut_Encode_Encoders = $PS["Data.Argonaut.Encode.Encoders"];
  var encodeJsonJson = {
      encodeJson: Control_Category.identity(Control_Category.categoryFn)
  };
  var encodeJsonJString = {
      encodeJson: Data_Argonaut_Encode_Encoders.encodeString
  };
  var encodeJsonInt = {
      encodeJson: Data_Argonaut_Encode_Encoders.encodeInt
  };
  var encodeJson = function (dict) {
      return dict.encodeJson;
  };
  var encodeJsonMaybe = function (dictEncodeJson) {
      return {
          encodeJson: Data_Argonaut_Encode_Encoders.encodeMaybe(encodeJson(dictEncodeJson))
      };
  };
  var encodeForeignObject = function (dictEncodeJson) {
      return {
          encodeJson: Data_Argonaut_Encode_Encoders.encodeForeignObject(encodeJson(dictEncodeJson))
      };
  };
  exports["encodeJson"] = encodeJson;
  exports["encodeJsonMaybe"] = encodeJsonMaybe;
  exports["encodeJsonInt"] = encodeJsonInt;
  exports["encodeJsonJString"] = encodeJsonJString;
  exports["encodeJsonJson"] = encodeJsonJson;
  exports["encodeForeignObject"] = encodeForeignObject;
})(PS);
(function(exports) {
  "use strict";

  //------------------------------------------------------------------------------
  // Non-indexed reads -----------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.unconsImpl = function (empty) {
    return function (next) {
      return function (xs) {
        return xs.length === 0 ? empty({}) : next(xs[0])(xs.slice(1));
      };
    };
  };

  //------------------------------------------------------------------------------
  // Indexed operations ----------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.indexImpl = function (just) {
    return function (nothing) {
      return function (xs) {
        return function (i) {
          return i < 0 || i >= xs.length ? nothing :  just(xs[i]);
        };
      };
    };
  };
})(PS["Data.Array"] = PS["Data.Array"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Array"] = $PS["Data.Array"] || {};
  var exports = $PS["Data.Array"];
  var $foreign = $PS["Data.Array"];
  var Data_Foldable = $PS["Data.Foldable"];
  var Data_Function = $PS["Data.Function"];
  var Data_Maybe = $PS["Data.Maybe"];
  var uncons = $foreign.unconsImpl(Data_Function["const"](Data_Maybe.Nothing.value))(function (x) {
      return function (xs) {
          return new Data_Maybe.Just({
              head: x,
              tail: xs
          });
      };
  });
  var index = $foreign.indexImpl(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  var foldl = Data_Foldable.foldl(Data_Foldable.foldableArray);
  exports["uncons"] = uncons;
  exports["index"] = index;
  exports["foldl"] = foldl;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Eq"] = $PS["Data.Eq"] || {};
  var exports = $PS["Data.Eq"];
  var eq = function (dict) {
      return dict.eq;
  };
  exports["eq"] = eq;
})(PS);
(function(exports) {
  "use strict";

  exports.intAdd = function (x) {
    return function (y) {
      /* jshint bitwise: false */
      return x + y | 0;
    };
  };

  exports.intMul = function (x) {
    return function (y) {
      /* jshint bitwise: false */
      return x * y | 0;
    };
  };
})(PS["Data.Semiring"] = PS["Data.Semiring"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Semiring"] = $PS["Data.Semiring"] || {};
  var exports = $PS["Data.Semiring"];
  var $foreign = $PS["Data.Semiring"];
  var semiringInt = {
      add: $foreign.intAdd,
      zero: 0,
      mul: $foreign.intMul,
      one: 1
  };
  var add = function (dict) {
      return dict.add;
  };
  exports["add"] = add;
  exports["semiringInt"] = semiringInt;
})(PS);
(function(exports) {
  "use strict";

  exports.unit = {};
})(PS["Data.Unit"] = PS["Data.Unit"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Data.Unit"] = $PS["Data.Unit"] || {};
  var exports = $PS["Data.Unit"];
  var $foreign = $PS["Data.Unit"];
  exports["unit"] = $foreign.unit;
})(PS);
(function(exports) {
  "use strict";

  exports.pureE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };
})(PS["Effect"] = PS["Effect"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Effect"] = $PS["Effect"] || {};
  var exports = $PS["Effect"];
  var $foreign = $PS["Effect"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Monad = $PS["Control.Monad"];                  
  var monadEffect = {
      Applicative0: function () {
          return applicativeEffect;
      },
      Bind1: function () {
          return bindEffect;
      }
  };
  var bindEffect = {
      bind: $foreign.bindE,
      Apply0: function () {
          return applyEffect;
      }
  };
  var applyEffect = {
      apply: Control_Monad.ap(monadEffect),
      Functor0: function () {
          return functorEffect;
      }
  };
  var applicativeEffect = {
      pure: $foreign.pureE,
      Apply0: function () {
          return applyEffect;
      }
  };
  var functorEffect = {
      map: Control_Applicative.liftA1(applicativeEffect)
  };
  exports["functorEffect"] = functorEffect;
  exports["applicativeEffect"] = applicativeEffect;
})(PS);
(function(exports) {
  "use strict";

  exports.log = function (s) {
    return function () {
      console.log(s);
    };
  };
})(PS["Effect.Console"] = PS["Effect.Console"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Effect.Console"] = $PS["Effect.Console"] || {};
  var exports = $PS["Effect.Console"];
  var $foreign = $PS["Effect.Console"];
  exports["log"] = $foreign.log;
})(PS);
(function(exports) {
  "use_strict";   
  exports.pMove = MOVE;
  exports.pWork = WORK;
  exports.pCarry = CARRY;
})(PS["Screeps.Const"] = PS["Screeps.Const"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Screeps.Const"] = $PS["Screeps.Const"] || {};
  var exports = $PS["Screeps.Const"];
  var $foreign = $PS["Screeps.Const"];
  exports["pMove"] = $foreign.pMove;
  exports["pWork"] = $foreign.pWork;
  exports["pCarry"] = $foreign.pCarry;
})(PS);
(function(exports) {
  "use strict";

  exports.getGameGlobal = function(){ return Game; }
  exports.createCreepImpl = function(structure){
      return function(parts){
        return function(role){
          return function(left){
            return function(right){
              return function(){
                var result = structure.createCreep(parts,{utility: 1, role: role});
                if (typeof result === "string"){
                    return right(result);
                } else {
                    return left(result);
                }
              }
            }
          }
        }
      }
  }
})(PS["Screeps.Game"] = PS["Screeps.Game"] || {});
(function(exports) {
  "use strict";

  // module Screeps.FFI

  exports.unsafeField = function(key){
      return function(obj){
          return obj[key];
      }
  }
  exports.unsafeGetFieldEff = function(key){
      return function(obj){
          return function(){
              return obj[key];
          }
      }
  }
  exports.unsafeSetFieldEff = function(key){
      return function(obj){
          return function(val){
              return function(){
                  obj[key] = val;
              }
          }
      }
  }

  exports.runThisFn1 = function(key){
    return function(self){
      return function(a){
        return self[key](a);
      }
    }
  }
  exports.toMaybeImpl = function (val, nothing, just){
      if(val === null || val === undefined){
          return nothing;
      } else {
          return just(val);
      }
  }
})(PS["Screeps.FFI"] = PS["Screeps.FFI"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Screeps.FFI"] = $PS["Screeps.FFI"] || {};
  var exports = $PS["Screeps.FFI"];
  var $foreign = $PS["Screeps.FFI"];
  var Data_Maybe = $PS["Data.Maybe"];                
  var toMaybe = function (n) {
      return $foreign.toMaybeImpl(n, Data_Maybe.Nothing.value, Data_Maybe.Just.create);
  };
  exports["toMaybe"] = toMaybe;
  exports["unsafeField"] = $foreign.unsafeField;
  exports["unsafeGetFieldEff"] = $foreign.unsafeGetFieldEff;
  exports["unsafeSetFieldEff"] = $foreign.unsafeSetFieldEff;
  exports["runThisFn1"] = $foreign.runThisFn1;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Screeps.Types"] = $PS["Screeps.Types"] || {};
  var exports = $PS["Screeps.Types"];
  var Control_Bind = $PS["Control.Bind"];
  var Data_Argonaut_Decode_Class = $PS["Data.Argonaut.Decode.Class"];
  var Data_Argonaut_Decode_Error = $PS["Data.Argonaut.Decode.Error"];
  var Data_Argonaut_Encode_Class = $PS["Data.Argonaut.Encode.Class"];
  var Data_Either = $PS["Data.Either"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Data_Show = $PS["Data.Show"];                                
  var RoleHarvester = (function () {
      function RoleHarvester() {

      };
      RoleHarvester.value = new RoleHarvester();
      return RoleHarvester;
  })();
  var RoleNULL = (function () {
      function RoleNULL() {

      };
      RoleNULL.value = new RoleNULL();
      return RoleNULL;
  })();
  var LoopGo = (function () {
      function LoopGo() {

      };
      LoopGo.value = new LoopGo();
      return LoopGo;
  })();
  var LoopStop = (function () {
      function LoopStop() {

      };
      LoopStop.value = new LoopStop();
      return LoopStop;
  })();
  var LoopNULL = (function () {
      function LoopNULL() {

      };
      LoopNULL.value = new LoopNULL();
      return LoopNULL;
  })();
  var showReturnCode = {
      show: function (v) {
          return Data_Show.show(Data_Show.showInt)(v);
      }
  };
  var roleList = [ RoleHarvester.value, RoleNULL.value ];
  var roleFromStr = function (v) {
      if (v === "RoleHarvester") {
          return new Data_Maybe.Just(RoleHarvester.value);
      };
      if (v === "RoleNULL") {
          return new Data_Maybe.Just(RoleNULL.value);
      };
      return Data_Maybe.Nothing.value;
  };
  var lsFromStr = function (v) {
      if (v === "loopGo") {
          return new Data_Maybe.Just(LoopGo.value);
      };
      if (v === "loopStop") {
          return new Data_Maybe.Just(LoopStop.value);
      };
      if (v === "loopNULL") {
          return new Data_Maybe.Just(LoopNULL.value);
      };
      return Data_Maybe.Nothing.value;
  };
  var eqRoles = {
      eq: function (v) {
          return function (v1) {
              if (v instanceof RoleNULL && v1 instanceof RoleNULL) {
                  return true;
              };
              if (v instanceof RoleHarvester && v1 instanceof RoleHarvester) {
                  return true;
              };
              if (v1 instanceof RoleNULL) {
                  return false;
              };
              if (v instanceof RoleNULL) {
                  return false;
              };
              throw new Error("Failed pattern match at Screeps.Types (line 138, column 1 - line 142, column 41): " + [ v.constructor.name, v1.constructor.name ]);
          };
      }
  };
  var encodeRole = {
      encodeJson: function (v) {
          if (v instanceof RoleHarvester) {
              return Data_Argonaut_Encode_Class.encodeJson(Data_Argonaut_Encode_Class.encodeJsonJString)("RoleHarvester");
          };
          if (v instanceof RoleNULL) {
              return Data_Argonaut_Encode_Class.encodeJson(Data_Argonaut_Encode_Class.encodeJsonJString)("RoleNULL");
          };
          throw new Error("Failed pattern match at Screeps.Types (line 144, column 1 - line 146, column 51): " + [ v.constructor.name ]);
      }
  };
  var encodeLoopStatus = {
      encodeJson: function (v) {
          if (v instanceof LoopGo) {
              return Data_Argonaut_Encode_Class.encodeJson(Data_Argonaut_Encode_Class.encodeJsonJString)("loopGo");
          };
          if (v instanceof LoopStop) {
              return Data_Argonaut_Encode_Class.encodeJson(Data_Argonaut_Encode_Class.encodeJsonJString)("loopStop");
          };
          if (v instanceof LoopNULL) {
              return Data_Argonaut_Encode_Class.encodeJson(Data_Argonaut_Encode_Class.encodeJsonJString)("loopNULL");
          };
          throw new Error("Failed pattern match at Screeps.Types (line 160, column 1 - line 163, column 48): " + [ v.constructor.name ]);
      }
  };
  var decodeRole = {
      decodeJson: function (json) {
          return Control_Bind.bind(Data_Either.bindEither)(Data_Argonaut_Decode_Class.decodeJson(Data_Argonaut_Decode_Class.decodeJsonString)(json))(function (string) {
              return Data_Either.note(new Data_Argonaut_Decode_Error.TypeMismatch("Role:"))(roleFromStr(string));
          });
      }
  };
  var decodeLoopStatus = {
      decodeJson: function (json) {
          return Control_Bind.bind(Data_Either.bindEither)(Data_Argonaut_Decode_Class.decodeJson(Data_Argonaut_Decode_Class.decodeJsonString)(json))(function (string) {
              return Data_Either.note(new Data_Argonaut_Decode_Error.TypeMismatch("LoopStatus:"))(lsFromStr(string));
          });
      }
  };
  exports["RoleHarvester"] = RoleHarvester;
  exports["RoleNULL"] = RoleNULL;
  exports["roleList"] = roleList;
  exports["LoopGo"] = LoopGo;
  exports["LoopStop"] = LoopStop;
  exports["LoopNULL"] = LoopNULL;
  exports["showReturnCode"] = showReturnCode;
  exports["eqRoles"] = eqRoles;
  exports["encodeRole"] = encodeRole;
  exports["decodeRole"] = decodeRole;
  exports["encodeLoopStatus"] = encodeLoopStatus;
  exports["decodeLoopStatus"] = decodeLoopStatus;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Screeps.Game"] = $PS["Screeps.Game"] || {};
  var exports = $PS["Screeps.Game"];
  var $foreign = $PS["Screeps.Game"];
  var Data_Argonaut_Encode_Class = $PS["Data.Argonaut.Encode.Class"];
  var Data_Either = $PS["Data.Either"];
  var Screeps_FFI = $PS["Screeps.FFI"];
  var Screeps_Types = $PS["Screeps.Types"];                
  var spawns = Screeps_FFI.unsafeField("spawns");
  var rawSpawnCreep = function (spawn) {
      return function (parts) {
          return function (name) {
              return function (role) {
                  var role$prime = Data_Argonaut_Encode_Class.encodeJson(Screeps_Types.encodeRole)(role);
                  return $foreign.createCreepImpl(spawn)(parts)(role$prime)(Data_Either.Left.create)(Data_Either.Right.create);
              };
          };
      };
  };
  var getObjectById = function (game) {
      return function (id) {
          return Screeps_FFI.toMaybe(Screeps_FFI.runThisFn1("getObjectById")(game)(id));
      };
  };
  var creeps = Screeps_FFI.unsafeField("creeps");
  exports["spawns"] = spawns;
  exports["creeps"] = creeps;
  exports["getObjectById"] = getObjectById;
  exports["rawSpawnCreep"] = rawSpawnCreep;
  exports["getGameGlobal"] = $foreign.getGameGlobal;
})(PS);
(function(exports) {
  "use strict";

  exports.getMemoryGlobal = function(){ return Memory; }      
  exports.getCreepsUtl = function(){
    var res = []
    for (var c in Memory.creeps) {
      res = res.concat(Memory.creeps[c]["utility"])
    }
    return res
  }
})(PS["Screeps.Memory"] = PS["Screeps.Memory"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Screeps.Memory"] = $PS["Screeps.Memory"] || {};
  var exports = $PS["Screeps.Memory"];
  var $foreign = $PS["Screeps.Memory"];
  var Data_Argonaut_Decode_Class = $PS["Data.Argonaut.Decode.Class"];
  var Data_Argonaut_Encode_Class = $PS["Data.Argonaut.Encode.Class"];
  var Data_Functor = $PS["Data.Functor"];
  var Effect = $PS["Effect"];
  var Screeps_FFI = $PS["Screeps.FFI"];                
  var set = function (dictEncodeJson) {
      return function (memoryGlobal) {
          return function (key) {
              return function (val) {
                  return Screeps_FFI.unsafeSetFieldEff(key)(memoryGlobal)(Data_Argonaut_Encode_Class.encodeJson(dictEncodeJson)(val));
              };
          };
      };
  };
  var get = function (dictDecodeJson) {
      return function (memoryGlobal) {
          return function (key) {
              return Data_Functor.map(Effect.functorEffect)(Data_Argonaut_Decode_Class.decodeJson(dictDecodeJson))(Screeps_FFI.unsafeGetFieldEff(key)(memoryGlobal));
          };
      };
  };
  exports["set"] = set;
  exports["get"] = get;
  exports["getMemoryGlobal"] = $foreign.getMemoryGlobal;
  exports["getCreepsUtl"] = $foreign.getCreepsUtl;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Creep"] = $PS["Creep"] || {};
  var exports = $PS["Creep"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Data_Argonaut_Decode_Class = $PS["Data.Argonaut.Decode.Class"];
  var Data_Argonaut_Decode_Combinators = $PS["Data.Argonaut.Decode.Combinators"];
  var Data_Argonaut_Encode_Class = $PS["Data.Argonaut.Encode.Class"];
  var Data_Array = $PS["Data.Array"];
  var Data_Either = $PS["Data.Either"];
  var Data_Eq = $PS["Data.Eq"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_Int = $PS["Data.Int"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Data_Semiring = $PS["Data.Semiring"];
  var Data_Show = $PS["Data.Show"];
  var Data_Unit = $PS["Data.Unit"];
  var Effect = $PS["Effect"];
  var Effect_Console = $PS["Effect.Console"];
  var Foreign_Object = $PS["Foreign.Object"];
  var Screeps_Const = $PS["Screeps.Const"];
  var Screeps_Game = $PS["Screeps.Game"];
  var Screeps_Memory = $PS["Screeps.Memory"];
  var Screeps_Types = $PS["Screeps.Types"];                
  var spawnCreep = function (spawn) {
      return function (parts) {
          return function (name) {
              return function (v) {
                  if (v instanceof Screeps_Types.RoleHarvester) {
                      return function __do() {
                          var res = Screeps_Game.rawSpawnCreep(spawn)(parts)(name)(Screeps_Types.RoleHarvester.value)();
                          if (res instanceof Data_Either.Left) {
                              return Effect_Console.log(Data_Show.show(Screeps_Types.showReturnCode)(res.value0))();
                          };
                          if (res instanceof Data_Either.Right) {
                              return Effect_Console.log(res.value0 + " created succesfully")();
                          };
                          throw new Error("Failed pattern match at Creep (line 145, column 5 - line 147, column 56): " + [ res.constructor.name ]);
                      };
                  };
                  if (v instanceof Screeps_Types.RoleNULL) {
                      return Control_Applicative.pure(Effect.applicativeEffect)(Data_Unit.unit);
                  };
                  throw new Error("Failed pattern match at Creep (line 141, column 1 - line 142, column 32): " + [ spawn.constructor.name, parts.constructor.name, name.constructor.name, v.constructor.name ]);
              };
          };
      };
  };
  var roleFilter = function (creep) {
      return false;
  };
  var numberOfRole = function (role) {
      return function (creeps) {
          return Foreign_Object.size(Foreign_Object.filter(roleFilter)(creeps));
      };
  };
  var fromMaybeToMaybeJson = function (v) {
      if (v instanceof Data_Maybe.Nothing) {
          return Data_Maybe.Just.create(Data_Argonaut_Encode_Class.encodeJson(Data_Argonaut_Encode_Class.encodeJsonInt)(-1 | 0));
      };
      if (v instanceof Data_Maybe.Just) {
          return Data_Maybe.Just.create(Data_Argonaut_Encode_Class.encodeJson(Data_Argonaut_Encode_Class.encodeJsonInt)(v.value0));
      };
      throw new Error("Failed pattern match at Creep (line 87, column 1 - line 87, column 46): " + [ v.constructor.name ]);
  };
  var findInd = function ($copy_v) {
      return function ($copy_v1) {
          return function ($copy_n) {
              var $tco_var_v = $copy_v;
              var $tco_var_v1 = $copy_v1;
              var $tco_done = false;
              var $tco_result;
              function $tco_loop(v, v1, n) {
                  if (v.length === 0) {
                      $tco_done = true;
                      return n;
                  };
                  var val$prime = (function () {
                      var v2 = Data_Array.uncons(v);
                      if (v2 instanceof Data_Maybe.Just) {
                          return v2.value0.head;
                      };
                      if (v2 instanceof Data_Maybe.Nothing) {
                          return Screeps_Types.RoleNULL.value;
                      };
                      throw new Error("Failed pattern match at Creep (line 96, column 18 - line 98, column 55): " + [ v2.constructor.name ]);
                  })();
                  var array$prime = (function () {
                      var v2 = Data_Array.uncons(v);
                      if (v2 instanceof Data_Maybe.Just) {
                          return v2.value0.tail;
                      };
                      if (v2 instanceof Data_Maybe.Nothing) {
                          return [  ];
                      };
                      throw new Error("Failed pattern match at Creep (line 99, column 18 - line 101, column 49): " + [ v2.constructor.name ]);
                  })();
                  var $38 = Data_Eq.eq(Screeps_Types.eqRoles)(v1)(val$prime);
                  if ($38) {
                      $tco_done = true;
                      return n;
                  };
                  $tco_var_v = array$prime;
                  $tco_var_v1 = v1;
                  $copy_n = n + 1 | 0;
                  return;
              };
              while (!$tco_done) {
                  $tco_result = $tco_loop($tco_var_v, $tco_var_v1, $copy_n);
              };
              return $tco_result;
          };
      };
  };
  var createCreep = function (spawn) {
      return function (name) {
          return spawnCreep(spawn)([ Screeps_Const.pWork, Screeps_Const.pCarry, Screeps_Const.pMove ])(name)(Screeps_Types.RoleHarvester.value);
      };
  };
  var calcRoleScore = function (creeps) {
      return function (v) {
          if (v instanceof Screeps_Types.RoleNULL) {
              return 0;
          };
          if (v instanceof Screeps_Types.RoleHarvester) {
              var harvs = numberOfRole(Screeps_Types.RoleHarvester.value)(creeps);
              var score = Data_Int.quot(1000)(harvs + 1 | 0);
              return score;
          };
          throw new Error("Failed pattern match at Creep (line 105, column 1 - line 105, column 54): " + [ creeps.constructor.name, v.constructor.name ]);
      };
  };
  var bestRole = function ($copy_v) {
      return function ($copy_v1) {
          return function ($copy_v2) {
              return function ($copy_role) {
                  var $tco_var_v = $copy_v;
                  var $tco_var_v1 = $copy_v1;
                  var $tco_var_v2 = $copy_v2;
                  var $tco_done = false;
                  var $tco_result;
                  function $tco_loop(v, v1, v2, role) {
                      if (v.length === 0) {
                          $tco_done = true;
                          return role;
                      };
                      if (v1.length === 0) {
                          $tco_done = true;
                          return role;
                      };
                      var scores$prime = (function () {
                          var v3 = Data_Array.uncons(v);
                          if (v3 instanceof Data_Maybe.Just) {
                              return v3.value0.tail;
                          };
                          if (v3 instanceof Data_Maybe.Nothing) {
                              return [  ];
                          };
                          throw new Error("Failed pattern match at Creep (line 128, column 20 - line 130, column 34): " + [ v3.constructor.name ]);
                      })();
                      var score$prime = (function () {
                          var v3 = Data_Array.uncons(v);
                          if (v3 instanceof Data_Maybe.Just) {
                              return v3.value0.head;
                          };
                          if (v3 instanceof Data_Maybe.Nothing) {
                              return 0;
                          };
                          throw new Error("Failed pattern match at Creep (line 131, column 20 - line 133, column 33): " + [ v3.constructor.name ]);
                      })();
                      var roles$prime = (function () {
                          var v3 = Data_Array.uncons(v1);
                          if (v3 instanceof Data_Maybe.Just) {
                              return v3.value0.tail;
                          };
                          if (v3 instanceof Data_Maybe.Nothing) {
                              return [  ];
                          };
                          throw new Error("Failed pattern match at Creep (line 122, column 20 - line 124, column 34): " + [ v3.constructor.name ]);
                      })();
                      var role$prime = (function () {
                          var v3 = Data_Array.uncons(v1);
                          if (v3 instanceof Data_Maybe.Just) {
                              return v3.value0.head;
                          };
                          if (v3 instanceof Data_Maybe.Nothing) {
                              return Screeps_Types.RoleNULL.value;
                          };
                          throw new Error("Failed pattern match at Creep (line 125, column 20 - line 127, column 40): " + [ v3.constructor.name ]);
                      })();
                      var $61 = score$prime > v2;
                      if ($61) {
                          $tco_var_v = scores$prime;
                          $tco_var_v1 = roles$prime;
                          $tco_var_v2 = score$prime;
                          $copy_role = role$prime;
                          return;
                      };
                      $tco_var_v = scores$prime;
                      $tco_var_v1 = roles$prime;
                      $tco_var_v2 = v2;
                      $copy_role = role;
                      return;
                  };
                  while (!$tco_done) {
                      $tco_result = $tco_loop($tco_var_v, $tco_var_v1, $tco_var_v2, $copy_role);
                  };
                  return $tco_result;
              };
          };
      };
  };
  var processCreepF = function (utl0) {
      return function (scores) {
          return function (roles) {
              return function (key) {
                  return function (val0) {
                      var utl = (function () {
                          var v = Data_Argonaut_Decode_Combinators.getField(Data_Argonaut_Decode_Class.decodeJsonInt)(val0)("utility");
                          if (v instanceof Data_Either.Left) {
                              return -1 | 0;
                          };
                          if (v instanceof Data_Either.Right) {
                              return v.value0;
                          };
                          throw new Error("Failed pattern match at Creep (line 76, column 20 - line 78, column 36): " + [ v.constructor.name ]);
                      })();
                      var rol = (function () {
                          var v = Data_Argonaut_Decode_Combinators.getField(Screeps_Types.decodeRole)(val0)("role");
                          if (v instanceof Data_Either.Left) {
                              return Screeps_Types.RoleNULL.value;
                          };
                          if (v instanceof Data_Either.Right) {
                              return v.value0;
                          };
                          throw new Error("Failed pattern match at Creep (line 79, column 20 - line 81, column 36): " + [ v.constructor.name ]);
                      })();
                      var alt = bestRole(scores)(roles)(0)(Screeps_Types.RoleNULL.value);
                      var ind = findInd(roles)(alt)(0);
                      var newUtl$prime = Data_Array.index(scores)(ind);
                      var newUtl = fromMaybeToMaybeJson(newUtl$prime);
                      var newRole = Data_Maybe.Just.create(Data_Argonaut_Encode_Class.encodeJson(Screeps_Types.encodeRole)(alt));
                      var val1 = Foreign_Object.update(function (v) {
                          return newRole;
                      })("role")(val0);
                      var val2 = Foreign_Object.update(function (v) {
                          return newUtl;
                      })("utility")(val1);
                      return val2;
                  };
              };
          };
      };
  };
  var processCreep = function (creeps) {
      return function (utl0) {
          return function (scores) {
              return function (roles) {
                  return Foreign_Object.mapWithKey(processCreepF(utl0)(scores)(roles))(creeps);
              };
          };
      };
  };
  var processCreeps = function (hash) {
      return function (game) {
          return function (mem) {
              var $68 = Foreign_Object.isEmpty(hash);
              if ($68) {
                  return function __do() {
                      Effect_Console.log("creating initial creep")();
                      var spawnslist = Screeps_Game.spawns(game);
                      var spawn1 = Foreign_Object.lookup("Spawn1")(spawnslist);
                      if (spawn1 instanceof Data_Maybe.Nothing) {
                          return Effect_Console.log("fatal error: no Spawn1")();
                      };
                      if (spawn1 instanceof Data_Maybe.Just) {
                          return createCreep(spawn1.value0)("Creep1")();
                      };
                      throw new Error("Failed pattern match at Creep (line 41, column 5 - line 45, column 40): " + [ spawn1.constructor.name ]);
                  };
              };
              return function __do() {
                  var creeputl = Screeps_Memory.getCreepsUtl();
                  var creeps$prime = Screeps_Memory.get(Data_Argonaut_Decode_Class.decodeForeignObject(Data_Argonaut_Decode_Class.decodeForeignObject(Data_Argonaut_Decode_Class.decodeJsonJson)))(mem)("creeps")();
                  var creeps = (function () {
                      if (creeps$prime instanceof Data_Either.Left) {
                          return Foreign_Object.empty;
                      };
                      if (creeps$prime instanceof Data_Either.Right) {
                          return creeps$prime.value0;
                      };
                      throw new Error("Failed pattern match at Creep (line 52, column 16 - line 54, column 38): " + [ creeps$prime.constructor.name ]);
                  })();
                  var utl0 = Data_Array.foldl(Data_Semiring.add(Data_Semiring.semiringInt))(0)(creeputl);
                  var roleScores = Data_Functor.map(Data_Functor.functorArray)(calcRoleScore(creeps))(Screeps_Types.roleList);
                  var newCreeps = processCreep(creeps)(utl0)(roleScores)(Screeps_Types.roleList);
                  Screeps_Memory.set(Data_Argonaut_Encode_Class.encodeForeignObject(Data_Argonaut_Encode_Class.encodeForeignObject(Data_Argonaut_Encode_Class.encodeJsonJson)))(mem)("creeps")(newCreeps)();
                  Screeps_Memory.set(Data_Argonaut_Encode_Class.encodeJsonInt)(mem)("utility")(utl0)();
                  return Effect_Console.log("U(n-1): " + (Data_Show.show(Data_Show.showInt)(utl0) + ", U(n): "))();
              };
          };
      };
  };
  exports["processCreeps"] = processCreeps;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var Creep = $PS["Creep"];
  var Data_Argonaut_Decode_Class = $PS["Data.Argonaut.Decode.Class"];
  var Data_Argonaut_Decode_Error = $PS["Data.Argonaut.Decode.Error"];
  var Data_Argonaut_Encode_Class = $PS["Data.Argonaut.Encode.Class"];
  var Data_Either = $PS["Data.Either"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Data_Unit = $PS["Data.Unit"];
  var Effect_Console = $PS["Effect.Console"];
  var Screeps_Game = $PS["Screeps.Game"];
  var Screeps_Memory = $PS["Screeps.Memory"];
  var Screeps_Types = $PS["Screeps.Types"];                
  var runCorpsegrindeer = function (game) {
      return function (memory) {
          return function (v) {
              if (v instanceof Screeps_Types.LoopGo) {
                  var creeps = Screeps_Game.creeps(game);
                  return function __do() {
                      Creep.processCreeps(creeps)(game)(memory)();
                      var tower = Screeps_Game.getObjectById(game)("TOWER_ID");
                      if (tower instanceof Data_Maybe.Just) {
                          return Effect_Console.log("tower code here")();
                      };
                      if (tower instanceof Data_Maybe.Nothing) {
                          return Data_Unit.unit;
                      };
                      throw new Error("Failed pattern match at Main (line 55, column 3 - line 57, column 25): " + [ tower.constructor.name ]);
                  };
              };
              if (v instanceof Screeps_Types.LoopStop) {
                  return Effect_Console.log("stopping loop");
              };
              if (v instanceof Screeps_Types.LoopNULL) {
                  return Effect_Console.log("null loop");
              };
              throw new Error("Failed pattern match at Main (line 49, column 1 - line 49, column 83): " + [ game.constructor.name, memory.constructor.name, v.constructor.name ]);
          };
      };
  };
  var initCorpsegrinder = function (memory) {
      return function (status) {
          return function __do() {
              Effect_Console.log("starting the corpsegrinder...")();
              Screeps_Memory.set(Data_Argonaut_Encode_Class.encodeJsonMaybe(Screeps_Types.encodeLoopStatus))(memory)("loopStatus")(new Data_Maybe.Just(status))();
              return Screeps_Memory.set(Data_Argonaut_Encode_Class.encodeJsonInt)(memory)("utility")(0)();
          };
      };
  };
  var areWeInit = function (memory) {
      return function __do() {
          var loopStatus = Screeps_Memory.get(Data_Argonaut_Decode_Class.decodeJsonMaybe(Data_Argonaut_Decode_Class.decodeJsonMaybe(Screeps_Types.decodeLoopStatus)))(memory)("loopStatus")();
          if (loopStatus instanceof Data_Either.Left) {
              Effect_Console.log(Data_Argonaut_Decode_Error.printJsonDecodeError(loopStatus.value0))();
              return Data_Maybe.Nothing.value;
          };
          if (loopStatus instanceof Data_Either.Right) {
              if (loopStatus.value0 instanceof Data_Maybe.Nothing) {
                  return new Data_Maybe.Just(Screeps_Types.LoopGo.value);
              };
              if (loopStatus.value0 instanceof Data_Maybe.Just) {
                  return loopStatus.value0.value0;
              };
              throw new Error("Failed pattern match at Main (line 37, column 19 - line 39, column 39): " + [ loopStatus.value0.constructor.name ]);
          };
          throw new Error("Failed pattern match at Main (line 33, column 3 - line 39, column 39): " + [ loopStatus.constructor.name ]);
      };
  };
  var main = function __do() {
      var game = Screeps_Game.getGameGlobal();
      var memory = Screeps_Memory.getMemoryGlobal();
      var initCheck = areWeInit(memory)();
      if (initCheck instanceof Data_Maybe.Nothing) {
          return initCorpsegrinder(memory)(Screeps_Types.LoopGo.value)();
      };
      if (initCheck instanceof Data_Maybe.Just) {
          return runCorpsegrindeer(game)(memory)(initCheck.value0)();
      };
      throw new Error("Failed pattern match at Main (line 23, column 3 - line 27, column 44): " + [ initCheck.constructor.name ]);
  };
  exports["main"] = main;
  exports["areWeInit"] = areWeInit;
  exports["initCorpsegrinder"] = initCorpsegrinder;
  exports["runCorpsegrindeer"] = runCorpsegrindeer;
})(PS);
PS["Main"].main();